# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


pool: AUS-POOL



steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.7.5'

- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azuredevops-pileline'
    backendAzureRmOverrideSubscriptionID: 'c316f505-7597-4175-b5db-d2949009d506'
    backendAzureRmResourceGroupName: 'prod-tfstate-rg'
    backendAzureRmStorageAccountName: 'prodstg005'
    backendAzureRmContainerName: 'tfstatefile'
    backendAzureRmKey: 'terraform.tfstate'
    workingDirectory: $(System.DefaultWorkingDirectory)/s


- task: TerraformTask@5
  displayName: terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azuredevops-pileline'
    environmentAzureRmOverrideSubscriptionID: 'c316f505-7597-4175-b5db-d2949009d506'
    workingDirectory: $(System.DefaultWorkingDirectory)/s

- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azuredevops-pileline'
    workingDirectory: $(System.DefaultWorkingDirectory)/s

    