trigger: none

parameters:
  - name: rg_name
    displayName: 'Resource Group Name'
    type: string
    default: 'my-rg'

  - name: location
    displayName: 'Azure Region'
    type: string
    default: 'eastus'

  - name: dev_stg
    displayName: 'Storage Account Name'
    type: string
    default: 'mystorageacct'

  - name: vnet_name
    displayName: 'Virtual Network Name'
    type: string
    default: 'my-vnet'

  - name: subnet
    displayName: 'Subnet Name'
    type: string
    default: 'my-subnet'

  - name: vm_name
    displayName: 'VM Name'
    type: string
    default: 'myvm'

# Use your custom self-hosted agent pool
pool:
  name: AUS-POOL

steps:

  - checkout: self

  # Terraform must already be installed on self-hosted runner
  - script: terraform version
    displayName: 'Check Terraform Version'

  - script: terraform init
    displayName: 'Terraform Init'

  - script: |
      terraform plan \
        -var="rg_name=${{ parameters.rg_name }}" \
        -var="location=${{ parameters.location }}" \
        -var="dev_stg=${{ parameters.dev_stg }}" \
        -var="vnet_name=${{ parameters.vnet_name }}" \
        -var="subnet=${{ parameters.subnet }}" \
        -var="vm_name=${{ parameters.vm_name }}"
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve \
        -var="rg_name=${{ parameters.rg_name }}" \
        -var="location=${{ parameters.location }}" \
        -var="dev_stg=${{ parameters.dev_stg }}" \
        -var="vnet_name=${{ parameters.vnet_name }}" \
        -var="subnet=${{ parameters.subnet }}" \
        -var="vm_name=${{ parameters.vm_name }}"
    displayName: 'Terraform Apply'
