name: Delete Azure Resource Group

on:
  workflow_dispatch:
    inputs:
      rg_name:
        description: 'Enter Resource Group name to delete'
        required: true
        default: 'my-rg'

jobs:
  delete-rg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL

      - name: Delete Resource Group
        run: |
          echo "Deleting Resource Group: ${{ github.event.inputs.rg_name }}"
          az group delete --name "${{ github.event.inputs.rg_name }}" --yes --no-wait